name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - run: ls
    
    - run: cat .nvmrc
    
    - name: Read .nvmrc
      run: "echo ##[set-env name=nvmrc;]$(cat .nvmrc)"

    - name: Use Node.js (.nvmrc)
      uses: actions/setup-node@v1
      with:
        node-version: ${NVMRC}
