name: CI

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    
    steps:
    - run: ls $RUNNER_TOOL_CACHE/Python
    - run: ls $RUNNER_TOOL_CACHE/PyPy
  mac:
    runs-on: macOS-latest
    
    steps:
    - run: ls $RUNNER_TOOL_CACHE/Python
    - run: ls $RUNNER_TOOL_CACHE/PyPy
  win:
    runs-on: windows-latest
    
    steps:
    - run: dir %RUNNER_TOOL_CACHE%\Python
    - run: dir %RUNNER_TOOL_CACHE%\PyPy
