name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - run: printenv
    
    - run: echo "::set-env name=FOO::BAR"
    
    - run: echo $FOO
    
    - run: echo "##[set-env name=FOO;]BAR"
    
    - run: echo $FOO
