name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/setup-node@master
      with:
        version: '10.x'
    - uses: actions/setup-node@master
      with:
        node-version: '10.x'
