name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - run: ls
    
    - run: cat .nvmrc
    
    - name: Read .nvmrc
      run: NVMRC=$(cat .nvmrc)

    - name: Use Node.js (.nvmrc)
      uses: actions/setup-node@v1
      with:
        node-version: ${NVMRC}
