name: CI

on: [push]

jobs:
  linux:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 8
        
    - run: node -v
    
    - run: echo $ImageVersion

  windows:

    runs-on: windows-latest
    
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 8
        
    - run: node -v
    
    - run: echo %ImageVersion%
    
    - run: dir %RUNNER_TOOL_CACHE%\node

  mac:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 8
        
    - run: node -v
    
    - run: echo $ImageVersion
